version: "3"
services:
  go:
    build: ./go
    command: sh -c "cd go && make"
    volumes:
      - .:/api
  python:
    build: ./python
    command: sh -c "cd python && make"
    volumes:
      - .:/api
